/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Matheus HEnry
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        //Inicio menu=new Inicio();
        //menu.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        menuVeiculos = new javax.swing.JMenu();
        menucadastrov = new javax.swing.JMenuItem();
        menulistv = new javax.swing.JMenuItem();
        menucadastrou = new javax.swing.JMenu();
        menucaduser = new javax.swing.JMenuItem();
        menulistuser = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuVeiculos.setText("Veiculos");

        menucadastrov.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menucadastrov.setText("Cadastro de Veiculos");
        menucadastrov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastrovActionPerformed(evt);
            }
        });
        menuVeiculos.add(menucadastrov);

        menulistv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        menulistv.setText("Lista de Veiculos");
        menulistv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulistvActionPerformed(evt);
            }
        });
        menuVeiculos.add(menulistv);

        jMenuBar2.add(menuVeiculos);

        menucadastrou.setText("Usuarios");

        menucaduser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menucaduser.setText("Cadastro de Usuarios");
        menucaduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucaduserActionPerformed(evt);
            }
        });
        menucadastrou.add(menucaduser);

        menulistuser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menulistuser.setText("Lista de Usuarios");
        menulistuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulistuserActionPerformed(evt);
            }
        });
        menucadastrou.add(menulistuser);

        jMenuBar2.add(menucadastrou);

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        jMenuBar2.add(MenuSair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        dispose();
    }//GEN-LAST:event_MenuSairActionPerformed

    private void menucadastrovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastrovActionPerformed
            VeiculoView cadv=new VeiculoView();
          //  this.areadetrabalho.add(cadv);
            cadv.setVisible(true);
            cadv.setLocationRelativeTo(null);
            
    }//GEN-LAST:event_menucadastrovActionPerformed

    private void menulistvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulistvActionPerformed
        ListaVeiculo listv=new ListaVeiculo();
        //this.areadetrabalho.add(listv);
        listv.setVisible(true);
        listv.setLocationRelativeTo(null);
    }//GEN-LAST:event_menulistvActionPerformed

    private void menucaduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucaduserActionPerformed
        CadastroUsuario caduser=new CadastroUsuario();
       // this.areadetrabalho.add(caduser);
        caduser.setVisible(true);
        caduser.setLocationRelativeTo(null);
    }//GEN-LAST:event_menucaduserActionPerformed

    private void menulistuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulistuserActionPerformed
        ListaUsuario listuser=new ListaUsuario();
       // this.areadetrabalho.add(listuser);
        listuser.setVisible(true);
        listuser.setLocationRelativeTo(null);
    }//GEN-LAST:event_menulistuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuVeiculos;
    private javax.swing.JMenu menucadastrou;
    private javax.swing.JMenuItem menucadastrov;
    private javax.swing.JMenuItem menucaduser;
    private javax.swing.JMenuItem menulistuser;
    private javax.swing.JMenuItem menulistv;
    // End of variables declaration//GEN-END:variables
}
